package main

// CNAME-based takeover fingerprints
var takeoverCNAME = map[string][]string{
	"GitHub Pages":   {"github.io"},
	"Heroku":         {"herokuapp.com", "herokussl.com", "herokudns.com"},
	"AWS S3":         {"s3.amazonaws.com", "s3-website"},
	"AWS CloudFront": {"cloudfront.net"},
	"Azure":          {"azurewebsites.net", "cloudapp.net", "azure-api.net", "azurefd.net", "blob.core.windows.net", "trafficmanager.net"},
	"Shopify":        {"myshopify.com"},
	"Tumblr":         {"tumblr.com"},
	"WordPress.com":  {"wordpress.com"},
	"Pantheon":       {"pantheonsite.io"},
	"Fastly":         {"fastly.net"},
	"Zendesk":        {"zendesk.com"},
	"Unbounce":       {"unbouncepages.com"},
	"Cargo":          {"cargocollective.com"},
	"Ghost":          {"ghost.io"},
	"Surge.sh":       {"surge.sh"},
	"Bitbucket":      {"bitbucket.io"},
	"Netlify":        {"netlify.app", "netlify.com"},
	"Vercel":         {"vercel.app", "now.sh"},
	"Fly.io":         {"fly.dev"},
	"Render":         {"onrender.com"},
	"Agile CRM":     {"agilecrm.com"},
	"Airee":          {"arecord.airee.com"},
	"Anima":          {"animaapp.io"},
	"Bigcartel":      {"bigcartel.com"},
	"Campaign Monitor": {"createsend.com"},
	"Desk":           {"desk.com"},
	"Freshdesk":      {"freshdesk.com"},
	"Helpjuice":      {"helpjuice.com"},
	"Helpscout":      {"helpscoutdocs.com"},
	"Intercom":       {"custom.intercom.help"},
	"JetBrains":      {"youtrack.cloud"},
	"Kinsta":         {"kinsta.cloud"},
	"LaunchRock":     {"launchrock.com"},
	"Readme":         {"readme.io"},
	"SmartJobBoard":  {"smartjobboard.com"},
	"StatusPage":     {"statuspage.io"},
	"Strikingly":     {"s.strikinglydns.com"},
	"Tave":           {"clientaccess.tave.com"},
	"TeamWork":       {"teamwork.com"},
	"Tictail":        {"tictail.com"},
	"Uberflip":       {"read.uberflip.com"},
	"UserVoice":      {"uservoice.com"},
	"Webflow":        {"proxy.webflow.com", "proxy-ssl.webflow.com"},
	"Wix":            {"wixdns.net"},
}

// HTTP body fingerprints for confirmed takeover
var takeoverBodyFingerprints = map[string]string{
	"GitHub Pages":   "There isn't a GitHub Pages site here",
	"Heroku":         "No such app",
	"AWS S3":         "NoSuchBucket",
	"Shopify":        "Sorry, this shop is currently unavailable",
	"Tumblr":         "There's nothing here",
	"WordPress.com":  "Do you want to register",
	"Pantheon":       "404 error unknown site",
	"Fastly":         "Fastly error: unknown domain",
	"Zendesk":        "Help Center Closed",
	"Ghost":          "The thing you were looking for is no longer here",
	"Surge.sh":       "project not found",
	"Bitbucket":      "Repository not found",
	"Netlify":        "Not Found - Request ID",
	"Unbounce":       "The requested URL was not found",
	"Strikingly":     "page not found",
	"LaunchRock":     "It looks like you may have taken a wrong turn",
	"Webflow":        "The page you are looking for doesn't exist",
	"Freshdesk":      "May be this is still fresh",
	"Helpjuice":      "We could not find what you're looking for",
	"Helpscout":      "No settings were found for this company",
	"StatusPage":     "You are being <a href",
	"UserVoice":      "This UserVoice subdomain is currently available",
	"Cargo":          "If you're moving your domain away from Cargo",
	"Campaign Monitor": "Double check the URL",
	"Agile CRM":     "Sorry, this page is no longer available",
	"Kinsta":         "No Site For Domain",
	"Readme":         "Project doesnt exist",
	"Azure":          "404 Web Site not found",
	"Vercel":         "The deployment could not be found",
	// Removed Render and Fly.io body fingerprints as "not found" is too generic and causes false positives
}
