github: H-A-R-S-H-V-A-R-D-H-A-N
custom: ["https://www.paypal.com/paypalme/harshvardhansingh611", "upi://pay?pa=harshvardhansinghrathore611@oksbi", "https://www.instagram.com/__h_a_r_s_h_v_a_r_d_h_a_n_"]
